# Generated by Django 3.1.2 on 2020-10-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='preview_text',
            field=models.TextField(default='', verbose_name='preview-text'),
            preserve_default=False,
        ),
    ]
